### ISSUE TITLE
Degree-Quant dataset transform bug

### ISSUE THREAD

**Issue by chaitjo** [camlsys/degree-quant#1]
Thank you for releasing the code! Found a bug in how transforms are composed for Degree-Quant when I customized the REDDIT example code to my own dataset:

https://github.com/camlsys/degree-quant/blob/5f056017bd0f4b1018842fb1a083ccf6c666e0b4/reddit_binary/dataset.py#L71

Had to change to:

```python
if dataset.transform is None:
    dataset.transform = dq_transform
else:
    dataset.transform = T.Compose([dataset.transform, dq_transform])
```

Otherwise, the transform becomes a list [None, ProbabilisticHighDegreeMask].

**Comment by chaitjo** [comment]
P.S. This doesn't apply for REDDIT_BINARY. This applies to datasets with rich node attributes.

**Comment by shyam196** [comment]
I added a comment for others, thanks for pointing out :-)
