### ISSUE TITLE
How can I train a model without Quantization?

### ISSUE THREAD

**Issue by AmeenAli** [camlsys/degree-quant#2]
Thank you for releasing the code!
How can I train a model without Quantization?
Thanks!

**Comment by shyam196** [comment]
Thanks for your interest :-)

https://github.com/camlsys/degree-quant/blob/257d6bcf25141f522d0dbfdd2ae9fdabb679f7e0/reddit_binary/main.py#L46

Use that `fp32` flag, and set any `ste_mode` flag (it will be ignored). The code is based off of PyG's repo: https://github.com/rusty1s/pytorch_geometric/blob/master/benchmark/kernel/main.py

That code should be faster I think.
