### ISSUE TITLE
reproducing results

### ISSUE THREAD

**Issue by AmeenAli** [camlsys/degree-quant#3]
Hi
I am trying to reproduce your results on reddit dataset using the 4 BITS configuration.
I run the following command : 
`python reddit_binary/main.py --int4 --gc_per --lr 0.001 --DQ --low 0.1 --change 0.1 --wd 4e-5 --epochs 200 --outdir ${RUN_DIR} --path ${DATA_DIR} | tee int4_dq.txt
`
However the results I get are 86.4, The paper says that for this config it should give 81.3 (table 3)
am I missing something ?
Thanks !

**Comment by shyam196** [comment]
There are some subtle changes between this code and the version we ran the experiments with. I remember trying this myself before releasing this code and also noticing that this version gives better results for Degree-Quant than the paper.

I don't think you're missing anything :-) -- the results in the paper are just a bit conservative.

**Comment by AmeenAli** [comment]
Hi,
Thank you for your reply,
If so, Any tips how to re-run the baselines (nQATW4A4 , QATW4AA) so I can make sure I have the new good numbers? ;-) 
Best

**Comment by shyam196** [comment]
Results only improved for degree-quant. Therefore re-running should not be necessary.
